### ISSUE TITLE
'GetMedian' is not defined

### ISSUE THREAD

**Issue by S4WRXTTCS** [a-kore/mlx90640-python#1]
I'm getting a "NameError: name 'GetMedian' is not defined when I try running it.

See below for the complete log. 
pi@raspberrypi:~/Rasp-I2C/thermal/mlx90640-python $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from MLX90640 import MLX90640 as MLX90640
>>> tcam = MLX90640.MLX90640()
>>> frame = tcam.GetFrameData()
/home/pi/Rasp-I2C/thermal/mlx90640-python/MLX90640/MLX90640.py:866: RuntimeWarning: invalid value encountered in sqrt
  Sx = np.sqrt(np.sqrt(Sx)) * KsTo[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Rasp-I2C/thermal/mlx90640-python/MLX90640/MLX90640.py", line 986, in GetFrameData
    frame[sub_cnt] = self.BadPixelsCorrection(self.outlierPixels, frame[sub_cnt], 1 )
  File "/home/pi/Rasp-I2C/thermal/mlx90640-python/MLX90640/MLX90640.py", line 685, in BadPixelsCorrection
    to[pixels[pix]] = GetMedian(ap,4)
NameError: name 'GetMedian' is not defined

**Comment by S4WRXTTCS** [comment]
I discovered that the Sensor I was using wasn't working correctly with the Pimoroni mlx90640 library so I tried a different sensor. This sensor works with that library, but now I'm getting a "NameError: name 'illchessSP is not defined" 

Here is the complete output. 
pi@raspberrypi:~/Rasp-I2C/thermal/mlx90640-python $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from MLX90640 import MLX90640 as MLX90640
>>> tcam = MLX90640.MLX90640()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Rasp-I2C/thermal/mlx90640-python/MLX90640/MLX90640.py", line 21, in __init__
    self.ExtractCILCParameters()
  File "/home/pi/Rasp-I2C/thermal/mlx90640-python/MLX90640/MLX90640.py", line 416, in ExtractCILCParameters
    ilChessSP[2] = illChessSP[2] - 32
NameError: name 'illChessSP' is not defined

**Comment by S4WRXTTCS** [comment]
I  just tried the narrow 55 degree version of this sensor with this Python Library, and it seems to work fine. At least in terms of loading up, and showing the thermal image. The thermal image always seem to have a hot area in the center. But, it does load up just fine with the narrow one and not the wide angle one. 

Has this been tested with the wide angle version?

**Comment by a-kore** [comment]
I've fixed the errors in the code, it was a couple of typos I missed, thanks for pointing them out.

I've used it with the wide angle thermal camera only and I was able to get the thermal image but some of the values at the corners of the wide angle view were off (much lower than expected).  I think it requires some correction factor for the edges of the image.
