### ISSUE TITLE
Vdd 

### ISSUE THREAD

**Issue by CobraYu** [a-kore/mlx90640-python#2]
In MLX90640.py
vdd = (resolutionCorrection * vdd - self.vdd25) / (self.kVdd + 3.3)
should be
vdd = (resolutionCorrection * vdd - self.vdd25) / (self.kVdd) + 3.3

**Comment by a-kore** [comment]
Yeah, that makes sense, it should be a bias factor.

Thanks, I've updated the master branch with the new code.
